### ISSUE TITLE
[1주차] 이슈 모음

### ISSUE THREAD

**Issue by ro-ssang** [Network-Dev-Study/docker-study#1]
## 이슈

* 도커 이미지와 도커 컴포즈 파일을 작성했으나 코드상에서 API 호출할 때, 도메인이 존재하지 않아 API 호출에 실패함 (`localhost:4001`)
* 코드에서 에러 처리가 잘 안되어 있음
* java를 조금씩 알아가는 중...

**Comment by woogieReal** [comment]
BFF 에서 API를 호출할 떄 도메인을 도커 서비스명으로 하면 돌아감

**Comment by ro-ssang** [comment]
## 서비스 명칭

* fe-web
* be-for-frontend
* be-board
* be-logger

**Comment by woogieReal** [comment]
## 로그 포맷

**Comment by ro-ssang** [comment]
docker-compose에서 이미지 빌드할 때, `context` 필드를 사용하면 된다.

```yaml
fe:
  build:
    context: ./fe
    dockerfile: Dockerfile
```
